version: "3"
services:
  db:
    image: mysql
    networks:
      - clubmanage
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/clubManage.sql:/docker-entrypoint-initdb.d
      - club-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: clubmanage
      MYSQL_USER: clubmanage
      MYSQL_PASSWORD: clubmanage

  client:
    build: ./client
    networks:
      - clubmanage
    ports:
      - 8080:8080
    depends_on:
     - backend

  backend:
    build: ./backend
    networks:
      - clubmanage
    depends_on:
      - db
  
networks:
  clubmanage:
volumes:
  club-data:
